### ISSUE TITLE
Listener is not working. Vaadin 7.5.1. Eclipse-Juno with vaadin plugin.

### ISSUE THREAD

**Issue by sergioszy** [alump/LabelButton#4]
Looks good  with link style underlining and pointer cursor, but when I click the label, nothing happen.

```
LabelButton label = new LabelButton("Caption", "Show notification",
            //event -> Notification.show("Clicked!")
            new LabelClickListener() {

                @Override
                public void onLabelClick(LabelClickEvent event) {
                    layout.addComponent(new Label("Thank you for clicking label"));
                    System.out.println("event");
                    Notification.show("Clicked!");
                }
            }
    );
```

I install it using Ivy and of course I compile the widgeset. 

There aren't details instructions. 

What I missing.

Thanks in advance.

**Comment by alump** [comment]
First idea that I have is... have you recompiled widgetset? If client side implementation of LabelButton is missing, labels will have correct look'n feel, but do not send click RPC messages.

**Comment by sergioszy** [comment]
Oh, yes, I think that is the problem, but Vaadin kills me for this task. Can't compile because I get a lot of differents errors. I  would try clean all caches and refresh, and see what happen ( this gonna take several hours with my internet )

**Comment by sergioszy** [comment]
Ivy clean all caches, refresh and resolve; fix all the problems.  Now is working OK. Thanks.
